"""create_rooms_tables

Revision ID: a61106e180fb
Revises: bfd9ab1c64d6
Create Date: 2026-05-08 21:24:05.061006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61106e180fb'
down_revision: Union[str, None] = 'bfd9ab1c64d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='roomstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_equipment_room_id'), ['room_id'], unique=False)

    op.create_table('room_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_images_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_images_room_id'))

    op.drop_table('room_images')
    with op.batch_alter_table('room_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_equipment_room_id'))

    op.drop_table('room_equipment')
    op.drop_table('rooms')
    # ### end Alembic commands ###
